# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89ef6b2607306e625b6dd5acf86b5101cd63b22d38b1a4a0e322da25ba84a0d0cabc2d25f113e7fdfbf5528b0af4adea15cbc3d8e1de032230dafdc0d8b9859

test:
  secret_key_base: 0e4cb8794d1a9462d532c81e6da1eb986bfc64cb841c44939d3f6169130a0d96293b5b4383510cdccd530915c199a7f8ef8cfcc567055a92f6d8441fa6babfae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
